VACCINE_SPOTTER_URL="https://www.vaccinespotter.org/api/v0/states/MN.json"

RESULT_FOUND_SLEEP_TIME=60

RESULT_NOT_FOUND_SLEEP_TIME=3

TWILIO_ACCOUNT_SID=""

TWILIO_TOKEN=""

TWILIO_PHONE_NUMBER=""

PHONE_NUMBER_TO_RECEIVE_NOTIFICATIONS=""

ZIP_CODE="55306"

DESIRED_DISTANCE=25